INITIAL_TX = 0
INITIAL_RX = 1
BROADCAST_FLOODING = 2
IDLE_FLOODING = 21
BROADCAST_ACK = 3
IDLE_BROADCAST = 31
SEND_PACKET = 4
IDLE_PACKET = 41
COMMUNICATION_OVER = 5
PASS_TOKEN = 6
RECEIVE_DATA = 7
WAIT_TOKEN = 8
IDLE = 9
END = -1

ACK_PACKET = 0
BROADCAST_DISCOVERY_PACKET = 1
BROADCAST_ACK_PACKET = 2
